Build with cmake (#60)
* Move to CMake

* Add multipule Executable

* Update CMAKe

* Remove dist

* Update Workflow

* update target

* Fix Unused warnings

* Add tree command

* Install tree

* add tree install

* Upload Artifact

* fix workflow

* replace PROJ_NAME

* fix naming

* Add Altenative windows compiler

* Update for Compiler Error C2059

* Fix error C2057  C2466 C2133

* Add constant size

* Add Constant Size

* Formatting and CMake Changes

* Add Cmake gitignore